# Site settings
title: thirsty_engineer
email: jtruty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   A personal blog about my software adventures that
   I find interesting enough to share. Also, probably beer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jtruty.github.io" # the base hostname & protocol for your site
twitter_username: jtruty
github_username:  jtruty

# Build settings
markdown: kramdown
highlighter: pygments

# Comments settings
comments :
  provider : disqus
  disqus :
    short_name : thirstyengineer
